### ISSUE TITLE
gg p claims it could not push, but commits are pushed to git just fine

### ISSUE THREAD

**Issue by dydx** [qw3rtman/gg#14]
Using a fresh install of GitGoodies and a folder with an existing repo, I made some changes, committed them, and pushed to GitHub.

> dydx@anubis > vim app.js
> dydx@anubis > gg a 
> [✔] Added everything!
> dydx@anubis >  gg c added notes about the delete endpoint not working on the frontend
> [✔] Added everything!
> [✔] Commited!
> "added notes about the delete endpoint not working on the frontend"

I receive the following message after trying to push to Github: 

> dydx@anubis > gg p
> [✖] Could not push commits. (may have to pull first, merge any conflicts, and then attempt to push again using the standard git command.)

I checked on it using regular Git commands and noticed that the changes were already pushed

> dydx@anubis ~/D/hackathon2> git push -u origin master
> ch master from origin.
> Everything up-to-date

**Comment by qw3rtman** [comment]
Fixed and published to npm. Update with `npm update -g gitgoodies`. :+1: 

Let me know if it works.

**Comment by dydx** [comment]
Just tried it out; seems to work great! Thanks!
