### ISSUE TITLE
gg s => 2 lines of "undefined"

### ISSUE THREAD

**Issue by nshtg** [qw3rtman/gg#15]
Using `gg s` (aswell as `gg status`) generates output with 2 lines of "undefined":

![screen shot 2015-03-09 at 13 25 53](https://cloud.githubusercontent.com/assets/5219415/6554815/e4d359b4-c65f-11e4-94e4-8755dced6131.png)

**Comment by 7LayersDesign** [comment]
Happens on my machine as well. 

![gg](https://cloud.githubusercontent.com/assets/433133/6561575/999b9804-c668-11e4-9fc6-11d530b68d4e.png)

**Comment by qw3rtman** [comment]
Published fix to npm, update with `npm update -g gitgoodies`.

Let me know if it works as expected.

**Comment by nshtg** [comment]
@qw3rtman
No. Additional, `gg s` on a non-git directory generates an error:

![screen shot 2015-03-09 at 22 26 14](https://cloud.githubusercontent.com/assets/5219415/6564746/63e95a5a-c6ab-11e4-9d32-8894ccfaffd1.png)

**Comment by nshtg** [comment]
@qw3rtman 
0.5.6 fixed the `undefined` problem, the problem with non-git directorys is still there:

![screen shot 2015-03-09 at 23 09 27](https://cloud.githubusercontent.com/assets/5219415/6565609/97c51570-c6b1-11e4-91bb-abe595ca340a.png)

**Comment by qw3rtman** [comment]
Glad the patch fixed it.

Will add a check for if the directory is a Git repository to the TODO.

**Comment by nshtg** [comment]
@qw3rtman  
Have to take that one back I'm afraid, via SSH it still bugs :/ Might be the locale though, give me a second to check it out.

![screen shot 2015-03-09 at 23 15 19](https://cloud.githubusercontent.com/assets/5219415/6565680/3d7509c6-c6b2-11e4-9fbd-9b294aa9c379.png)

**Comment by nshtg** [comment]
Indeed I can confirm, setting the server language to something different than english breaks your script. Might want to use porcelain commands instead of simple text comparison in the future ^^

**Comment by qw3rtman** [comment]
@maschs, I plan on switching to native C bindings via `libgit2`, which is more reliable and would be language-agnostic, in the near future. That should fix the language issue. :smile:
