### ISSUE TITLE
gg cl returns could not clone repository

### ISSUE THREAD

**Issue by NitroXenon** [qw3rtman/gg#16]
I enter command : 
`gg cl https://github.com/NitroXenon/node-push-test.git`
it returns `[✖] Could not clone repository.`

but when I enter command:
`gg cl http://github.com/NitroXenon/node-push-test.git`
it returns `[✔] Cloned into 'node-push-test'...`

Is it a problem of https?

**Comment by qw3rtman** [comment]
Fixed and published to npm. Update with `npm update -g gitgoodies`. :+1:

**Comment by NitroXenon** [comment]
ok this is great since I need to delete that 's' every time I clone a repo. Thx a lot for fixing this bug

**Comment by qw3rtman** [comment]
Sure thing! Thanks for the catch! :smile:
