### ISSUE TITLE
How do I make my shell look like yours in the gg screenshots?

### ISSUE THREAD

**Issue by gavinengel** [qw3rtman/gg#17]
It looks cool

**Comment by calebmeyer** [comment]
This is an oh my zsh theme:
https://github.com/robbyrussell/oh-my-zsh/wiki/themes#miloshadzic

@qw3rtman, you might mention that in your readme somewhere.

**Comment by qw3rtman** [comment]
Yep, @calebmeyer is on point with that.

Using the [zsh shell](http://www.zsh.org/) with the miloshadzic [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) theme.

I'll add this to the FAQs, as well.

**Comment by gavinengel** [comment]
thank you both!
