### ISSUE TITLE
Problem cloning

### ISSUE THREAD

**Issue by semasad** [qw3rtman/gg#18]
When I clone a repository with `gg clone git@git.–––.–:~/git/––––.git` or `gg cl git@git.–––.–:~/git/––––.git` the console prints the error `[✖] Could not clone repository.`.

**Comment by qw3rtman** [comment]
Added handling for cloning via SSH and published to npm. Update with `npm update -g gitgoodies`.

Let me know if it works as expected.

**Comment by semasad** [comment]
Yes, it works! Thanks!
