### ISSUE TITLE
exports.cloneURL is missed

### ISSUE THREAD

**Issue by Semigradsky** [qw3rtman/gg#21]
It looks like function `exports.cloneURL` is missed in commit 3d1b2d254abadac11df04fb55d945720d5e2d302

Search: https://github.com/qw3rtman/gg/search?utf8=%E2%9C%93&q=cloneURL&type=Code

**Comment by qw3rtman** [comment]
Fixed and published to npm. Update with `npm update -g gitgoodies`.

Thanks for the catch! :+1:
