### ISSUE TITLE
Git log black on black

### ISSUE THREAD

**Issue by ramarnat** [qw3rtman/gg#23]
I have terminal in a dark theme, the git log shows the name and date in dark ansi colors
![screenshot](https://cloud.githubusercontent.com/assets/88762/6596369/fcb6c488-c7c9-11e4-8f47-694404bcadd6.png)

**Comment by qw3rtman** [comment]
I was originally planning on circumventing this issue by inverting the colors; however, it seems inverting the colors also changes the background.

We may be able to determine the background color and adjust the primary text color that way, but I'm not clear on how to determine the terminal color in NodeJS.

Any ideas would be appreciated.

**Comment by ramarnat** [comment]
I switched to using the afterglow theme, which is slightly better. The Afterglow theme has versions for iTerm (https://github.com/mbadolato/iTerm2-Color-Schemes) and Atom (https://github.com/Kikobeats/afterglow-monokai-syntax). Since Atom is written in node, maybe there are some indications in the two correlated themes to figure out how to set the Terminal colors?

Sorry not a Node guy so don't have a better idea.

**Comment by qw3rtman** [comment]
Thanks for the information! I'll add this to the TODO. :smile:
