### ISSUE TITLE
Error on pushing but the push was performed

### ISSUE THREAD

**Issue by semasad** [qw3rtman/gg#24]
I made a commit, I add all the changes `gg a` then `gg c -a COMMIT TEXT`and then `gg p`, but the terminal prints `[✖] Could not push commits.`. When I check if the commit was uploaded with `gg log`the last commit was my commit that I couldn't upload because it prints an "error".

```
[71792bc8d621e24c1974b81473f34d6b9778dea4]
|- Sebastian Masad <***@***.com>
|- Wed Mar 11 16:00:23 2015 -0300
|- COMMIT TEXT
```

**Comment by qw3rtman** [comment]
For starters, `gg c -a COMMIT TEXT` is not a valid `gg` command, although it seems to work just fine, for some odd reason. For future reference, using `gg c` automatically adds all files and then commits, while `gg cn` simply commits.

Running `gg p` again _should_ work; however, I'd like to solve this problem. Could you send me the output of `git push` itself?

Also, what platform are you on?

Thanks! :smile:

**Comment by semasad** [comment]
@qw3rtman I try to make a commit, I add all the files (`gg a`) and then I want to write a commit, this happened:

`semasad:milandia semasad$ gg c COMMIT MESSAGE
[✔] Added everything!
[✖] Could not commit changes. Try again if there was a large amount of changes to add.`

This is a new error, but when I use the traditional git this output the push:

``` semasad:milandia semasad$ git push
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

In Git 2.0, Git will default to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Counting objects: 11, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 484 bytes | 0 bytes/s, done.
Total 6 (delta 5), reused 0 (delta 0)
To git@git.nursoft.cl:~/git/milandia.git
   d306ca7..b1a3ab0  master -> master ```

I'am using OSX Mavericks.

**Comment by qw3rtman** [comment]
I think I understand how to fix this now. Could you send me a screenshot of the entire `git push` output in a terminal?

**Comment by semasad** [comment]
![screenshot 2015-03-12 14 45 11](https://cloud.githubusercontent.com/assets/2313518/6624189/79193d6a-c8c6-11e4-820c-68843a15c9ee.png)

**Comment by qw3rtman** [comment]
Just published a fix to npm, update with `npm update -g gitgoodies`.

Let me know if it works. :smile:

**Comment by semasad** [comment]
@qw3rtman It work's! Thanks :smile:

**Comment by qw3rtman** [comment]
Excellent! Also, for future reference, this error arose due to a rare case in which the default push remote was not specified (as outlined in your `git push` output).

Once we switch over to [libgit2](https://libgit2.github.com), errors such as this one will be much less common. :smile:
