### ISSUE TITLE
How to revert back?

### ISSUE THREAD

**Issue by ahmadawais** [qw3rtman/gg#25]
I am not a pro Command line user. But I always use Git in Command line. I've read about such stuff earlier, what stops me from jumping ahead is what if, I end up with something where there I get help for normal git codes and I won't be able to find how to do that in new zsh terminal. How would I revert? Could you tell? How to revert if something goes wrong?

**Comment by qw3rtman** [comment]
`zsh` is not a requirement for this package; you can use any shell with `gg` and you'll be fine.

If you'd like to switch back to the default shell (generally `bash`), simply type the name of the shell in `zsh`. Suppose your shell is bash, you would type `bash` in the shell and it would take you to a bash shell.

All Git commands that work in `bash` **will work in `zsh`**.

In addition, you can use `git` alongside `gg`, with no interference. They are separate commands. So you could run a `git` command you find online and then run a `gg` command with no problem, and vice versa.

Hope that answers your question. :smile:

**Comment by ahmadawais** [comment]
Thanks for such a detailed answer. I am going to try it now :)
