### ISSUE TITLE
gg pl dosen't pull

### ISSUE THREAD

**Issue by semasad** [qw3rtman/gg#27]
When I type `gg pl` GG doesn't make the pull and in the terminal appears the `[✔] Pulled!`

**Comment by qw3rtman** [comment]
Could you provide some more information, such as your platform and what `git pull` outputs? I am unable to reproduce this error.

Thanks! :smile:

**Comment by ianwalter** [comment]
Same issue here. I get:

```
gg pl origin develop
[~] Everything is already up-to-date.
```

`git pull origin develop` pulls a bunch of changes.
Using:
- git version 2.3.3
- io.js v1.6.2
- OS X Yosemite

**Comment by qw3rtman** [comment]
Sadly, this Node.js version of Git Goodies will no longer be maintained. On the bright side, I have recently completed a version of [Git Goodies in Shell](https://github.com/qw3rtman/gg) with more features, more speed, and less bugs. I believe it solves this issue as well; if you could let me know for sure, that'd be great. :smile:
