### ISSUE TITLE
Enhancement: When pull appears what files have change

### ISSUE THREAD

**Issue by semasad** [qw3rtman/gg#28]
When I make `git pull`git prints what files have been changed, would be awesome when I make `gg pl`GG show me what file have been changed.

**Comment by qw3rtman** [comment]
I am still considering whether or not to show what files have changed or not. As the main purpose of `gg` is simplicity, it would clutter up the interface to have a listing of files.

I was thinking a verbose option (`gg pl v`) might be useful to those who would like to see what has been pulled, added, committed, etc. What do you think?

Regardless, this enhancement would be very tricky until we switch to [`libgit2`](https://libgit2.github.com/), which will happen in the near future.

**Comment by semasad** [comment]
It would be awesome to have that command :)

**Comment by qw3rtman** [comment]
Excellent. I'll add it to the TODO. :+1:
