### ISSUE TITLE
Error while commiting : [✖] Could not commit changes. 

### ISSUE THREAD

**Issue by SeeTwoDev** [qw3rtman/gg#29]
Hi,

i like the gg idea and all but we can't seem to be able to make it work.
We keep running into this problem : [✖] Could not commit changes. Try again if there was a large amount of changes to add.

I'm not sure what kind of info we could add he beside that it runs on Ubuntu 14.04 and that normal commits work.

**Comment by qw3rtman** [comment]
Could you paste your `git commit -m message` output?

Thanks! :smile:

**Comment by SeeTwoDev** [comment]
gg c Update packages
[✔] Added everything!
[✖] Could not commit changes. Try again if there was a large amount of changes to add.

git commit -m "Update packages"
[master 4980eaf] Update packages
 7 files changed, 90 insertions(+), 25 deletions(-)
 create mode 100755 core/class.forfait_categorie.php

**Comment by sylvainbaronnet** [comment]
Same problem.

**Comment by aexis-b** [comment]
Great plugin using it daily...

Similar issue as noted above:

$ gg c test
[✔] Added everything!
[✖] Could not commit changes. Try again if there was a large amount of changes to add.

but this works:

$ git commit -m "test"
[develop ab1da5a] test
 1 file changed, 99 insertions(+), 99 deletions(-)
 rewrite npm-debug.log (72%)
$

**Comment by engineersamuel** [comment]
Same issue here as well.

**Comment by qw3rtman** [comment]
Hey, all.

I am working on a new version of Git Goodies that is Node-independent and runs much more smoothly, not to mention that it fixes pretty much every issue (including this one).

I'm very glad you find Git Goodies useful. :)

I will inform you all here when I release the new version.

**Comment by engineersamuel** [comment]
Awesome, thanks @qw3rtman I use Git Goodies every single day, saves me a lot of time over the long haul.

**Comment by qw3rtman** [comment]
I have recently completed the version of [Git Goodies in Shell](https://github.com/qw3rtman/gg) with more features, more speed, and less bugs. I believe it solves this issue as well; if you could let me know for sure, that'd be great.

I'm very glad to hear that Git Goodies is helping other developers. Hopefully this new version of Git Goodies can help you save even more time. :smile:

**Comment by engineersamuel** [comment]
Just installed and tested, fixes the gg c issue and works brilliantly fast, thank you @qw3rtman!

**Comment by qw3rtman** [comment]
That's great, glad to hear. :+1:
