### ISSUE TITLE
When I have a pending commit gg don't pull

### ISSUE THREAD

**Issue by semasad** [qw3rtman/gg#30]
When I have a pending commit and I run `gg pl`GG outputs: `[✔] Pulled!`but the pull was not performed. When I use the traditional command `git pull`the system returns:

Updating a07c89f..5728eba
error: Your local changes to the following files would be overwritten by merge:
    app/views/home/catalog.html.erb
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by qw3rtman** [comment]
Support for merging hasn't been implemented yet; however, it is in the TODO.

I have added handling for this error, so it should output an error instead of `[✔] Pulled!`.

Published to npm (update with `npm update -g gitgoodies`), let me know if it works as expected. :smile:
