### ISSUE TITLE
gg s Undefined Output

### ISSUE THREAD

**Issue by niedzielski** [qw3rtman/gg#32]
1. Clone a repo. For example, `git clone https://github.com/wikimedia/apps-android-wikipedia.git`.
2. Enter the repo.
3. Run `gg s`.
4. Note the output appears incorrect:
   
   branch   | master
   position | up-to-date
   
   undefined
   undefined

**Comment by themartorana** [comment]
+1 - If it means anything, I'm using ZSH instead of bash.

**Comment by niedzielski** [comment]
I just did an `npm install -g gitgoodies` again and it magically started working :/
