### ISSUE TITLE
Missing --version Option

### ISSUE THREAD

**Issue by niedzielski** [qw3rtman/gg#33]
gg does not supply a `--version` / `-v` option to print version information.

**Comment by qw3rtman** [comment]
Added in this feature and published to npm. Update with `npm update -g gitgoodies`. I wasn't able to get it working with `--version` or `-v` for some reason. Will switch to a more robust CLI framework in the near future, likely [commander](https://www.npmjs.com/package/commander), which should fix this issue.

This command also checks if `gg` is up-to-date and informs the user of this status.

Let me know if it works as expected. :smile:

**Comment by niedzielski** [comment]
Seems to work fine!
