### ISSUE TITLE
"gg s" on not-git dir produced error

### ISSUE THREAD

**Issue by Iwan-Zotow** [qw3rtman/gg#35]
/usr/lib/node_modules/gitgoodies/lib/gg.js:279
    switch (status[1].split(' ')[3]) {
                     ^
TypeError: Cannot read property 'split' of undefined
    at /usr/lib/node_modules/gitgoodies/lib/gg.js:279:22
    at ChildProcess.exithandler (child_process.js:751:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)

**Comment by qw3rtman** [comment]
Could you paste the output of `git status`? A screenshot would be better so I can see where the linebreaks are.

**Comment by Iwan-Zotow** [comment]
here is the output of git status:
fatal: Not a git repository (or any of the parent directories): .git

**Comment by Iwan-Zotow** [comment]
![image](https://cloud.githubusercontent.com/assets/8153556/6838883/c1eeb2d4-d336-11e4-814e-7faeb54c24aa.png)

**Comment by Iwan-Zotow** [comment]
Screenshot in one comment up. Gitgoodies are v0.6.4

**Comment by qw3rtman** [comment]
@jackamo is currently working on adding a check for if a Git repository exists in the current directory or not. See #31.

Thanks for letting us know about it. :+1:

**Comment by moondowner** [comment]
I'm having a similar problem:
```
D:\Test\test\docs>gg s
branch   | undefined

C:\Users\martin\AppData\Roaming\npm\node_modules\gitgoodies\lib\gg.js:279
    switch (status[1].split(' ')[3]) {
                      ^
TypeError: Cannot call method 'split' of undefined
    at C:\Users\martin\AppData\Roaming\npm\node_modules\gitgoodies\lib\gg.js:279:23
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

And here's the output from `git status`:
```
$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        Main.txt

nothing added to commit but untracked files present (use "git add" to track)
```

So, the git repository is there (not related to #31).
