### ISSUE TITLE
Could not pull commits. (may have to pull using the standard git command to handle merge conflicts.)

### ISSUE THREAD

**Issue by letunglam** [qw3rtman/gg#37]
It shows this error `[✖] Could not pull commits. (may have to pull using the standard git command to handle merge conflicts.)`. When I pull with standard git command, it shows `Current branch master is up to date.`

I am using OSX 10.10

**Comment by qw3rtman** [comment]
Sadly, this Node.js version of Git Goodies will no longer be maintained. On the bright side, I have recently completed a version of [Git Goodies in Shell](https://github.com/qw3rtman/gg) with more features, more speed, and less bugs. I believe it solves this issue as well; if you could let me know for sure, that'd be great. :smile:
