### ISSUE TITLE
List changed files?

### ISSUE THREAD

**Issue by jmooo** [qw3rtman/gg#41]
A regular 'git status' shows what files have been changd, but 'gg s' just shows there are some changed files, but not what. Is there a gg command which lists the changes?

**Comment by qw3rtman** [comment]
`gg` is designed to be very minimalistic in order to increase productivity by decreasing the amount of time you spend reading the outputs of Git commands. Implementing this sort of verbosity would detract from that feature and render `gg` very similar to Git itself.
