### ISSUE TITLE
Add shortcut for "git remote"

### ISSUE THREAD

**Issue by AchoArnold** [qw3rtman/gg#45]
Something like "gg r" will do

**Comment by qw3rtman** [comment]
What purpose do you intent this to solve? From my experience, `git remote` is mainly used to set configuration and manage remotes.

**Comment by AchoArnold** [comment]
yes and thats why I'll like a shortcut for this. I'll be happy if this can be incoporated. But I totally understand if you don't find it important.

**Comment by qw3rtman** [comment]
Could you give me any use-cases that aren't more efficient simple due to not having to type `git remote` but rather `gg r`?

**Comment by AchoArnold** [comment]
I can't give you one. I taught that was the point of this tool (to help us type less)?

**Comment by qw3rtman** [comment]
I think an interesting new feature, along with having to type less, would warrant adding a new command.

Do you have specific special new features for `gg r` in mind?
