### ISSUE TITLE
Alias for gg command

### ISSUE THREAD

**Issue by brunowego** [qw3rtman/gg#48]
If user have installed [https://github.com/robbyrussell/oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh), will catch a problem with alias for `gg` command, to fix it, open the file `git.plugin.zsh`:

``` bash
vim ~/.oh-my-zsh/plugins/git/git.plugin.zsh
```

And comment the line with:

``` zsh
alias gg='git gui citool'
```

There is not much to be done about it.

---

More details about output of command:

``` bash
where gg

gg: aliased to git gui citool
/usr/local/bin/gg
```

**Comment by evelop** [comment]
I think it is better to put `unalias gg` at the end of your `~/.zshrc`
Like that it might not get deleted with an update of oh-my-zsh.

**Comment by brunowego** [comment]
Well thinking, great idea @evelop :+1:

**Comment by qw3rtman** [comment]
Great idea! I'll this to the README under "Installation". :+1:
