### ISSUE TITLE
GitHub clone default username

### ISSUE THREAD

**Issue by AndersDJohnson** [qw3rtman/gg#57]
It'd be great if easy cloning from GitHub via #8 had some way of defaulting a to a persisted username for the current user, so we could download our own repos by name only, like [hub](https://github.com/github/hub).

**Comment by qw3rtman** [comment]
Great idea! Will add this to the TODO and keep this issue open for ideas and discussion. :+1: 

I've been considering adding some form of authentication to make working with GitHub (and related services) easier with Git Goodies.

**Comment by AndersDJohnson** [comment]
It could be as simple as checking for a config variable, e.g. `git config --get github.user` - so that if that exists, and if we were defaulting to `https://github.com/${arg}.git` as in #8, and `arg` didn't have a forward slash, then prepend the value of that config variable plus a `/` to `arg` before wrapping.
User would then just configure `git config --global github.user adjohnson916` if they wanted that functionality.

**Comment by qw3rtman** [comment]
Great idea, implemented! :+1:
