### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by davisvagris** [qw3rtman/gg#58]
Hello, Thanks to build nice app :+1: But i see some issues:
1) gg cl don't work on bitbucket ssh
2) When i use `gg c "message"` get error `/usr/local/bin/gg: line 281: [: report: binary operator expected`

**Comment by qw3rtman** [comment]
The second issue should be fixed now thanks to #59 and #63. If you could you make a new issue specifically for your first issue and give more detail, that would be very helpful.

Thanks!
