### ISSUE TITLE
Error when installing on debian

### ISSUE THREAD

**Issue by AchoArnold** [qw3rtman/gg#61]
when I run `curl -fsSL git.io/gg.sh | sh` I get the error

```
sh: 18: Syntax error: "(" unexpected (expecting "}")
```

`uname -a` gives

```
Linux secret-ninja 4.0.0-2-amd64 #1 SMP Debian 4.0.8-2 (2015-07-22) x86_64 GNU/Linux
```

**Comment by sirvon** [comment]
+1

``` bash
uname -a
```

``` bash
Linux creator 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2+deb7u2 x86_64 GNU/Linux
```

**Comment by qw3rtman** [comment]
Seems to be an issue with using `($var)` syntax to split a string into an array by space. I've replaced this syntax with the `IFS` method.

Let me know if it's working now.

**Comment by professorjamesmoriarty** [comment]
Debian and Ubuntu doesnt use "sh" as you'd expect. Rather they use dash. This is what I assume is the cause of this problem.

```
$ ls -al /bin/sh
lrwxrwxrwx 1 root root 4 Jan  5  2015 /bin/sh -> dash
```

http://manpages.ubuntu.com/manpages/hardy/man1/dash.1.html

Replacing sh with bash (which should be on most installs) lets the install function as expected.
