### ISSUE TITLE
Are there any plans to update this? Currently it won't work in ZSH.

### ISSUE THREAD

**Issue by didier** [qw3rtman/gg#75]
When trying to use the `gg`command, it spawns an instance of Tk -> `DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.`

**Comment by qw3rtman** [comment]
oh-my-zsh already assigns an alias to `gg`. Adding `unalias gg` to your `.zshrc` should fix this

**Comment by didier** [comment]
Oh, that worked. Can't believe it was that easy 😆
