### ISSUE TITLE
Is there a way to selectively git add the files ?

### ISSUE THREAD

**Issue by Lujaw** [qw3rtman/gg#9]
I added the individual files using git add command  but when using gg c, it automatically added all the files. Is that a bug or feature?

**Comment by qw3rtman** [comment]
This was a feature originally implemented before the ability to add specific files via `gg a` was even added. As the primary objective of `gg` is to expedite Git workflow by doing the heavy lifting for you, having `gg c` add all the files before committing the changes means you don't have to add all the files beforehand.

This is definitely a problem now, as `gg` has become more flexible and now allows adding specific files. Any ideas of where to go from here?

**Comment by calebmeyer** [comment]
add all is my 90% case. You could probably add a flag to gg c (--no-add, maybe?) that committed whatever files were already staged, or warned if no files were staged.

**Comment by qw3rtman** [comment]
Sounds like a good idea to me.

How about `gg cn` for committing without adding all first and the default `gg c` (and related aliases, such as `gg ci` and `gg commit`) for committing with adding all first?

**Comment by Lujaw** [comment]
gg cn seems like a good idea.

**Comment by qw3rtman** [comment]
Implemented and published to npm. Update with `npm update -g gitgoodies`.

Let me know if it works as expected.
